### ISSUE TITLE
Widget Settings - To-do-list

### ISSUE THREAD

**Issue by DavefromPrifina** [prifina/app-desktop#129]
*User Story*
As a user of the To-do-list widget, I want to be able to select a theme so I can customize my experience 

**Loom walktrough URL**: [Video name](video Link)
**Figma Prototype URL**: [User Story Name](User Story Link)
**Figma Designer View**: ["Asset Name"]([Figma Link](https://www.figma.com/file/5KxymqnFE8HsousvCWveoS/A1.2.-Display-App-v.MVP?node-id=2678%3A32920))

*Includes:* 
**Relevant user story Google Doc**: (User Story Link)

**Completion Status**
- [ ] UX Logic
- [ ] Design System Components 
- [ ] Visual Design
- [ ] Text Copy
- [ ] Data Model
- [ ] Back-end functions documentation
- [ ] User Story Documentation finalised
- [ ] Milestone Version updates
