### ISSUE TITLE
Data cloud landing page 

### ISSUE THREAD

**Issue by DavefromPrifina** [prifina/app-desktop#148]
*Screenshot of the Issue*

### **Data cloud landing page **

*Summary narrative*
This task does not  have a specific user story but it exists to ensure the design of the Data Cloud landing page clearly communicates;

- The tasks users can perform 
- The value they can get by adding/ connecting data (Why?)

As well as making sure we have all the:

- Visual assets
- Copy content

### **Tasks:** 

**Add data manually** 
this feature allows users to add anything they like (there are file type limitations). 

**Link data sources** 
this feature allows users set up automated API based data retrieval for sources we support. 

### Layout decision

The layout to best support the two user tasks and familiarize user with DC quickly  is a Split screen with an announcement banner at the top.

### Copy 

- [ ] Banner copy - this banner should give context to the role of DC within Prifina's ecosystem think 'the engine that Powers your platform' 
- [ ] Data uploader - right side for manual uploads -- think 'why would I do this?' what is the value?
- [ ] Connect data - left side, small amount of text to go over a graphic - value prop for data connection 

### Visual 
 - [ ] Banner graphic - graphic to support message in banner 
- [ ] Connect data -  graphic to support message in 'connect data' container

**Visual component design**: ["Asset Name"](Figma Link)

**Completion Status**
- [ ] UX logic
- [ ] Copy
- [ ] Visual design

*Guidelines:* ["GitHub Issue Card Template"](https://docs.google.com/document/d/1kyk7G7o19gZscVL-TEA1p1nVmP2NYk0Gf2w_MCcgXgk/edit#heading=h.antcpmcoy5u2)

**Comment by DavefromPrifina** [comment]
@mmlampinen  assigned to you for copy 
@MikeFil49 for UI and visual

**Comment by DavefromPrifina** [comment]
@mmlampinen prefilled form ready, link in issue

**Comment by mmlampinen** [comment]
ps let's avoid abbreviations where not necessary. I was scratching my head thinking who is "DC" for a while

**Comment by DavefromPrifina** [comment]
@MikeFil49 the text copy is ready for this screen - click the spreadsheet link in the issue. Can you add the text to the design and then move it into the PVSD final push file.

**Comment by MikeFil49** [comment]
@DavefromPrifina Done. Moved it near the Current focus section.

**Comment by DavefromPrifina** [comment]
Copy locked
