### ISSUE TITLE
To-do-list /  Data requirements tab

### ISSUE THREAD

**Issue by DavefromPrifina** [prifina/app-desktop#159]
### *Individual widget listing page - Battleship*
_Data requirements tab_

This issue is a 'child' of  #123  and exists to ensure that we have for each widget listing:

- All required visual assets
- All required copy

*No user data page template:* 
![Template](https://user-images.githubusercontent.com/81253284/127351142-53508284-31cd-4f3b-836e-5d7b503003b2.jpg)

This set of screens are for widgets which do not require any user-held data;

1. Weatherly 
2. To-do-list
3. Battleship
4. Browser chat
5. Anon search
6. Data Uploader
7. Clock widget

### Visual 
We need graphics to complement the copy and to help explain how the widget uses data. In the template image above these are  NO.6

![image](https://user-images.githubusercontent.com/81253284/127375154-80aeebdf-0996-49f3-8faa-df8a07433894.png)

_User-generated data graphic_

- [ ] User-generated data graphic

### Copy

Each widget listing page has an associated Google form for inputting/updating content which is linked to a spreadsheet. 

Google form - all known/assumed content has been pre-filled (you should see this when you load the form) change pre-filled answers to update and answer un-answered questions. When you submit the form an entry will be added to the spreadsheet 

[To-do-list  - content form with pre-filled answers 
](https://docs.google.com/forms/d/e/1FAIpQLSf5cgo8-iRAgkUD9PeuW0iltu5Qlo1vonndCtkl5iLASFcUrA/viewform?usp=pp_url&entry.1556768153=User-generated&entry.4439422=None+needed&entry.1979004665=Lists+%26+tasks&entry.1666039128=None+needed)
[Content sheet 
](https://docs.google.com/spreadsheets/d/1rqWaeusM4d_1Dg5cmQCGBpjkucJuNe6e9fxYFtUC6v0/edit?usp=sharing)
### **Copy final checklist**

- [x] 1. Data type tags 
- [ ] 2. Data requirement paragraph
- [x] 3. Public data requirement
- [x] 4. User-generated data requirement 
- [x] 5. User-held data requirement

**Completion Status**
- [x] UX Logic
- [ ] Visual Design
- [ ] Text Copy

**Comment by mmlampinen** [comment]
added copy

**Comment by DavefromPrifina** [comment]
Updated Public & User-generated data graphic - now uses generic widget/data source @MikeFil49

**Comment by DavefromPrifina** [comment]
On hold for now --- revisit task once we have first release and widget designs
